apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: app-hpa
  namespace: dev
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    kind: Deployment
    name: app-deployment
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 60
---