apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-quota
  namespace: dev
spec:
  hard:
    limits.cpu: 4
    limits.memory: 4Gi 
    requests.cpu: 2
    requests.memory: 2Gi
    pods: 10
    services: 5
---